### ISSUE TITLE
일기장 페이지 (이모션 글자, 텍스트 글자 수, 크기조절)

### ISSUE THREAD

**Issue by suno0140** [suno0140/BulletBox_FE#47]
## Description

일기장 페이지 (이모션 글자, 텍스트 글자 수, 크기조절)

## Todo

- [x] 이모션 아래 감정 상태 글자 추가
- [x] 텍스트 최대 글자 수 500으로 변경
- [x] 텍스트 아리아 전체 크기조절(화면 안넘어가게)
