### ISSUE TITLE
카테고리 UI / 기능

### ISSUE THREAD

**Issue by suno0140** [suno0140/BulletBox_FE#7]
## Description

마이페이지 에서 내 카테고리 UI 및 기능 추가

## Todo

- [x] 카테고리 UI
- [x] 카테고리 추가 UI
- [x] 카테고리 수정 UI
- [x] 카테고리 삭제 Ui
- [x] 카테고리 조회, 추가, 수정, 삭제 API 연동
