### ISSUE TITLE
검색 페이지 / UI 및 기능

### ISSUE THREAD

**Issue by suno0140** [suno0140/BulletBox_FE#9]
## Description

검색페이지 UI 및 기능 추가

## Todo

- [x] 검색 페이지 UI
- [x] 검색 조회 기능
- [x] 검색 디바운스 적용
